### ISSUE TITLE
community toolkit.mvvm for Validation

### ISSUE THREAD

**Issue by lostluna1** [WinUICommunity/WinUICommunity#43]
Has anyone ever used CommunityToolkit.mvvm in combination with the validation framework of this project

I need a minimum example, thank you

in my xaml:

```css
<TextBox
    Width="200"
    Margin="5"
    wuc:Validation.ErrorTemplate="{StaticResource ValidationTemplate}"
    wuc:Validation.ValidationPropertyName="EmployeeCode"
    PlaceholderText="工号"
    Text="{x:Bind Path=ViewModel.Employee.EmployeeCode, Mode=TwoWay}" />
``` 

ViewModels:
```c#
[ObservableProperty]
private Employee _employee = new();
``` 
Models:
```c#
public partial class Employee : ObservableValidator
{
    public string? EmployeeId
    {
        get; set;
    }

    public string? EmployeeCode
    {
        get; set;
    }

    public string? Name
    {
        get; set;
    }

    public string? Remark
    {
        get; set;
    }

    public DateTime CreateTime
    {
        get; set;
    }

    public DateTime UpdateTime
    {
        get; set;
    }

    public bool? IsDeleted
    {
        get; set;
    }

    public bool? IsSelected
    {
        get; set;
    }

    public string? Department
    {
        get; set;
    }

    public string? Position
    {
        get; set;
    }
}
```
